#!/usr/bin/env python3
"""
This script automates the creation of language learning materials from personal diary entries.
It processes diary entries written in a primary language, translates them into a study
language, and generates TPRS (Teaching Proficiency Through Reading and Storytelling) lessons.

The script is organized into two main functionalities: Diary Handling and TPRS Creation.

## Core Functionalities:

1.  **Diary Entry Processing (`DiaryHandler`)**:
    *   **Input**: Users can write diary entries in a Markdown file or be prompted
        interactively to provide sentences in their primary language and optionally
        attempt translations into the study language.
    *   **OpenAI Integration**:
        *   Translates primary language sentences to the study language.
        *   Provides grammatical tips and explanations for the translations.
        *   Generates a daily title for diary entries based on their content.
    *   **Output**:
        *   A main Markdown file (e.g., `diary.md`) consolidating all processed diary entries.
        *   Individual daily Markdown files for easier review.
        *   Diary entries written to `diary.json` for spaced-repetition review in the web app.

2.  **TPRS Lesson Generation (`TprsCreation` & `TprsVariantHandler`)**:
    *   **Input**: Uses the processed diary entries (study language sentences).
    *   **OpenAI Integration**: Generates TPRS-style questions and answers (Q&A) for
        each sentence to reinforce comprehension and active recall.
    *   **TPRS Variants**: Creates multiple versions of TPRS content:
        *   **Standard**: Basic Q&A for the translated sentences.
        *   **Enhanced**: Rewrites sentences and Q&A for improved clarity, fluency,
          and naturalness for TTS.
        *   **Future Tense**: Transforms sentences and Q&A into the future tense.
        *   **Present Tense**: Transforms sentences and Q&A into the present tense.
    *   **Output**: For each TPRS variant:
        *   A main Markdown file consolidating all TPRS Q&A for that variant.
        *   Individual daily Markdown files for each variant.
        *   TTS audio lessons (`.mp3`) for each day's TPRS content, allowing for
          listening practice.

## Workflow Summary:

1.  **Configuration**: Script behavior is controlled via a `config.yaml` file (e.g.,
    language settings, OpenAI keys, TTS preferences, output paths).
2.  **Diary Input**: User provides diary entries (manually in Markdown or via prompts).
3.  **Diary Processing**: `DiaryHandler` translates sentences, adds tips, generates titles,

4.  **TPRS Generation**: `TprsCreation` takes the processed diary sentences and, for each
    configured TPRS variant:
    a.  Generates specific Q&A using OpenAI.
    b.  Writes TPRS content to Markdown files.
    c.  Creates TTS audio lessons.

## Diary Entry Template (example for `diary.md`):

# YYYY (Year)

## YYYY/MM/DD: [Optional Title Generated by Script]
- **[Sentence in primary language]**
  <span style="color: #C70039 ">Forsøk</span>: [User's trial translation in study language - optional]
  <span style="color: #097969">Rettelse</span>: [Script-generated translation in study language]
  <span style="color: #dda504">Tips</span>: [Script-generated learning tips]

(Repeat for more sentences)
"""

import hashlib
import json
import logging
import os
import time
from collections import defaultdict
from datetime import datetime
from functools import cached_property
from pathlib import Path
from typing import Callable

import yaml
from openai import OpenAI
from platformdirs import user_config_dir

from lingodiary.diary_json import (
    AudioTiming,
    Sentence,
    VariantSet,
    QA,
    ReviewingState,
    SentenceBlock,
    get_day,
    load_diary_json,
    save_diary_json,
    upsert_day,
)

APP_NAME = "lingoDiary"
CONFIG_FILE = "config.yaml"

# Maps the variant handler name (as used in TprsVariantHandler.variant_name)
# to the JSON key on VariantSet.
VARIANT_NAME_MAP: dict[str, str] = {
    "Standard": "original",
    "Enhanced": "enhanced",
    "Future": "future",
    "Present": "present",
}
# Maps the variant handler name to the audio-path key in diary.json.
# Currently identical to VARIANT_NAME_MAP but kept separate so the two
# can diverge independently.
VARIANT_AUDIO_KEY_MAP: dict[str, str] = {
    "Standard": "original",
    "Enhanced": "enhanced",
    "Future": "future",
    "Present": "present",
}


class DiaryHandler:
    def __init__(self, config_path=None):
        """Initializes the DiaryHandler with configuration and sets up necessary attributes.

        Args:
            config_path (str, optional): Path to the configuration file.
                                         Defaults to None, which then uses the default user config path.
        """
        self.config = DiaryHandler.load_config(config_path=config_path)
        self.output_dir = self.config["output_dir"]
        self.backup_dir = os.path.join(self.output_dir, ".backup")
        self.tts_model = self.config["tts"]["model"]
        self.titles_dict = {}

        self.setup_logging()
        self.validate_arguments()

    @staticmethod
    def load_config(config_path=None):
        """Loads the YAML configuration file.

        Args:
            config_path (str, optional): The path to the configuration file.
                                         If None, uses the default user config path.
                                         Defaults to None.

        Returns:
            dict: The loaded configuration as a dictionary.

        Raises:
            FileNotFoundError: If the configuration file is not found.
        """
        if config_path is None:
            config_path = Path(user_config_dir(APP_NAME)).joinpath(CONFIG_FILE)

        if os.path.exists(config_path):
            with open(config_path) as f:
                conf = yaml.safe_load(f) or {}

            # Ensure 'languages' key exists
            if "languages" not in conf:
                conf["languages"] = {}
            if "output_script" not in conf["languages"]:
                conf["languages"]["output_script"] = "native"

            # Derive output_dir and json_diary_path defaults from config location
            username = os.path.basename(os.path.dirname(os.path.abspath(config_path)))
            data_root = os.getenv("DATA_ROOT", "/data")
            default_output_dir = os.path.join(data_root, username)

            conf.setdefault("output_dir", default_output_dir)
            conf.setdefault(
                "json_diary_path",
                os.path.join(conf["output_dir"], "diary.json"),
            )

            return conf

        logger = logging.getLogger(__name__)
        logger.error(f"Please create configuration file {config_path}")
        raise FileNotFoundError

    def setup_logging(self):
        """Sets up logging for the application.

        Configures a logger with both file and stream handlers if not already set up.
        Logs are written to 'output.log' in the configured output directory.
        """
        # Check if logger is already set up to avoid duplicate handlers
        logger = logging.getLogger(__name__)

        if not any(
            isinstance(handler, logging.FileHandler) for handler in logger.handlers
        ):
            log_formatter = logging.Formatter(
                "%(asctime)s - %(levelname)s - %(message)s"
            )

            # Create file handler to log into output.log (flush after every record)
            class FlushingFileHandler(logging.FileHandler):
                def emit(self, record):
                    super().emit(record)
                    self.flush()

            os.makedirs(self.output_dir, exist_ok=True)
            file_handler = FlushingFileHandler(
                os.path.join(self.config["output_dir"], "output.log")
            )
            file_handler.setFormatter(log_formatter)

            # Create stream handler for console output
            stream_handler = logging.StreamHandler()
            stream_handler.setFormatter(log_formatter)

            # Set logger level to INFO
            logger.setLevel(
                logging.INFO
            )  # You can change this to DEBUG for more verbosity
            logger.addHandler(file_handler)
            logger.addHandler(stream_handler)

        self.logging = logger

    def close_logging(self):
        """Closes all logging handlers associated with this instance's logger."""
        if hasattr(self, "logging"):
            logger = self.logging
            handlers = logger.handlers[:]
            for handler in handlers:
                handler.close()
                logger.removeHandler(handler)

    def stop(self):
        """Stops the DiaryHandler by closing logging resources."""
        self.close_logging()

    def validate_arguments(self):
        """Validates paths and creates required directories.

        Sets self.new_diary = True if diary.json does not yet exist.
        """
        json_path = self.config.get("json_diary_path")
        if json_path and not os.path.exists(json_path):
            self.logging.info(
                f"diary.json not found at {json_path} — treating as a new diary."
            )
            os.makedirs(os.path.dirname(json_path), exist_ok=True)
            self.new_diary = True
        else:
            self.new_diary = False

        if self.output_dir:
            if not os.path.exists(self.output_dir):
                try:
                    os.makedirs(self.output_dir, exist_ok=True)
                except Exception as e:
                    raise ValueError(
                        f"Failed to create output directory: {self.output_dir}. Error: {e}"
                    )

        if self.backup_dir:
            os.makedirs(self.backup_dir, exist_ok=True)

    def generate_unique_id(self, input_string, length=9):
        """Generates a unique ID based on a hash of the input string.

        Args:
            input_string (str): The string to hash.
            length (int, optional): The length of the unique ID to generate.
                                    Defaults to 9.

        Returns:
            int: A unique ID of the specified length.
        """
        # Hash the string using SHA256
        hash_object = hashlib.sha256(input_string.encode("utf-8"))

        # Convert the hash to an integer
        hash_int = int(hash_object.hexdigest(), 16)

        # Take a portion of the integer and ensure it's the desired length
        unique_id_str = str(hash_int % (10**length))
        return unique_id_str.zfill(length)

    @cached_property
    def _openai_client(self) -> OpenAI:
        """Lazily created, shared OpenAI client for this handler instance."""
        return OpenAI(api_key=self.config["openai"]["key"], timeout=60)

    def _openai_call(
        self,
        messages: list[dict],
        *,
        system: str = "You are a helpful assistant.",
        json_mode: bool = False,
        retries: int = 3,
    ) -> str:
        """Call the OpenAI chat completions API and return the raw content string.

        Retries up to *retries* times on transient errors (network, rate-limit,
        server error) with exponential back-off (2 s, 5 s, 10 s).

        Args:
            messages: List of ``{"role": ..., "content": ...}`` dicts (user turns only;
                      the system message is prepended automatically from *system*).
            system:   System prompt string.
            json_mode: If ``True``, sets ``response_format={"type": "json_object"}``.
            retries:  Maximum number of attempts.

        Returns:
            Raw content string from the model.

        Raises:
            RuntimeError: If all retries are exhausted or the model returns empty content.
        """
        full_messages = [{"role": "system", "content": system}] + messages
        kwargs: dict = dict(
            model=self.config["openai"]["model"],
            messages=full_messages,
        )
        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}

        delays = [2, 5, 10]
        last_exc: Exception | None = None
        for attempt in range(retries):
            try:
                response = self._openai_client.chat.completions.create(**kwargs)
                content = response.choices[0].message.content
                if not content:
                    raise RuntimeError(
                        f"OpenAI returned empty content "
                        f"(finish_reason={response.choices[0].finish_reason!r})"
                    )
                return content
            except Exception as exc:
                last_exc = exc
                if attempt < retries - 1:
                    wait = delays[min(attempt, len(delays) - 1)]
                    self.logging.warning(
                        f"[OpenAI] Attempt {attempt + 1}/{retries} failed: {exc}. "
                        f"Retrying in {wait}s…"
                    )
                    time.sleep(wait)
        raise RuntimeError(f"OpenAI call failed after {retries} attempts") from last_exc

    def openai_create_day_title(self, sentences_block_dict):
        """Generates a catchy title for a day's diary entries using OpenAI.

        The title is based on the study language sentences for that day.

        Args:
            sentences_block_dict (dict): A dictionary where keys are sentence numbers
                                         and values are dictionaries containing sentence details,
                                         including "study_language_sentence".

        Returns:
            str: The generated title in the study language.
        """
        sentences = [
            entry["study_language_sentence"] for entry in sentences_block_dict.values()
        ]

        prompt = f"""
        Given the following sentences (written as python array) in {self.config["languages"]["study_language"]},
        could you create in no more than 5/6 words a catchy title about them?
        - Don't use commas, exclamation marks, column.
        - if you need a comma, use a -
        - Use the {self.config["languages"]["output_script"]} script for all generated text in {self.config["languages"]["study_language"]}.


        give the result as text in {self.config["languages"]["study_language"]}

        The sentences are:
            {sentences}
        """

        self.logging.info("[OpenAI] Creating day title (this may take a moment)...")
        output = self._openai_call([{"role": "user", "content": prompt}])
        self.logging.info(f"[OpenAI] Day title done: {output.strip()[:80]}")
        return output

    def openai_translate_sentence(self, sentence_dict):
        """Translates a sentence from the primary language to the study language using OpenAI.

        Also generates learning tips for the translation. The request considers the user's
        gender for grammatically correct translations.

        Args:
            sentence_dict (dict): A dictionary containing the "primary_language_sentence"
                                  and "study_language_sentence_trial".

        Returns:
            dict: A dictionary containing the "primary_language_sentence",
                  "study_language_sentence" (the translation), "tips", and
                  "study_language_sentence_trial".
        """
        prompt = f"""
        You need to translate a sentence given in {self.config["languages"]["primary_language"]} into {self.config["languages"]["study_language"]}].
        The output should be a JSON dictionary where:
        - The main key is "sentence".
        - Under "sentence" is another dictionnary with 3 keys:
            - the "primary_language_sentence" to translate.
            - the "study_language_sentence" is the translation you need to create
            - the "tips" is some tips to explain the translation. The tips should be written in {self.config["languages"]["primary_language"]}.
        - **DO NOT invent extra words or modify the original meaning of the sentence.**
        - If the primary_language_sentence is not grammatically correct, or if there are minor issues, you could fix the grammar and ponctuation only.
        - if the primary_language_sentence has reference about I, as me, you should know that my gender is {self.config["gender"]} as this will be useful to have the proper grammar and ending on words
        - Generate a sentence that is ready to be spoken by a Text-to-Speech system. Expand abbreviations that are not normally spoken as-is (e.g., 'km/h' should become 'kilometers per hour'), but keep common spoken abbreviations (e.g., 'AM', 'PM') unchanged. Ensure the result is natural for TTS. Adapt abbreviation expansion appropriately to the target language {self.config["languages"]["study_language"]}.
        - In addition, when generating text for non-English languages, expand non-spoken abbreviations according to natural usage in that language (e.g., in French, 'km/h' ➔ 'kilomètres par heure').
        - Use the {self.config["languages"]["output_script"]} script for the "study_language_sentence" field in {self.config["languages"]["study_language"]}.

        Example output format:

        {{
            "sentence": {{
                    "study_language_sentence": "Torsdag var en spesiell dag. Vi dro til Lakseøya, en ganske fancy restaurant.",
                    "primary_language_sentence": "Thursday was a special day. We went to the Salmon Isle. A pretty fancy restaurant.",
                    "tips": "\"pretty fancy\" kan oversettes som \"ganske fancy\" eller \"ganske fin\", men \"fancy\" brukes også ofte på norsk",
                }}
        }}


        ### Now generate the dictionnary for this sentences  "{sentence_dict["primary_language_sentence"]}"
        """

        # Make the API call
        self.logging.info(
            f"[OpenAI] Translating: {sentence_dict['primary_language_sentence'][:80].strip()}..."
        )
        output = json.loads(
            self._openai_call([{"role": "user", "content": prompt}], json_mode=True)
        )
        self.logging.info(
            f"[OpenAI] Translation done: {output['sentence'].get('study_language_sentence', '')[:80].strip()}"
        )
        output["sentence"]["study_language_sentence_trial"] = sentence_dict[
            "study_language_sentence_trial"
        ]
        return output["sentence"]

    def get_all_days_title(self, diary_dict):
        """Gets or generates titles for all days in diary_dict.

        Uses titles already in diary.json if present; falls back to OpenAI only when
        all sentences for that day are translated.
        """
        titles_dict = {}

        for date_diary in diary_dict:
            existing_title = self.titles_dict.get(date_diary)
            if existing_title:
                titles_dict[date_diary] = existing_title
                continue

            sentences = diary_dict[date_diary].get("sentences", {}).values()
            if all(s.get("study_language_sentence") for s in sentences):
                title_day = self.openai_create_day_title(
                    diary_dict[date_diary]["sentences"]
                )
                self.logging.info(
                    f"created title with openai for {date_diary} - {title_day}"
                )
            else:
                self.logging.info(
                    f"Title not created for {date_diary} as sentences are not yet fully translated"
                )
                title_day = None
            titles_dict[date_diary] = title_day

        self.titles_dict = titles_dict
        return titles_dict

    def write_diary_json(self, diary_dict):
        """Writes processed diary entries to the JSON file.

        Args:
            diary_dict (dict): A dictionary of diary entries, keyed by date.
        """
        self.get_all_days_title(diary_dict)
        self.titles_dict = {
            k: (v if v is not None else "") for k, v in self.titles_dict.items()
        }
        self._write_json_diary(diary_dict)

    def _write_json_diary(self, diary_dict):
        """Write diary entries to the JSON file if json_diary_path is configured.

        Preserves existing SRS state for entries that already exist in the JSON.
        Silently skips if json_diary_path is not set in config.
        """
        json_path = self.config.get("json_diary_path")
        if not json_path:
            return

        try:
            diary_json = load_diary_json(json_path)

            for date_obj, day_data in diary_dict.items():
                date_str = date_obj.strftime("%Y/%m/%d")
                title = self.titles_dict.get(date_obj, "")
                sentences = day_data.get("sentences", {})

                entries = []
                for idx, sentence_dict in sorted(sentences.items()):
                    entry = Sentence(
                        index=int(idx),
                        input_language_sentence=sentence_dict.get(
                            "primary_language_sentence", ""
                        ).strip(),
                        user_trial_translation=sentence_dict.get(
                            "study_language_sentence_trial", ""
                        ).strip(),
                        output_language_translation=sentence_dict.get(
                            "study_language_sentence", ""
                        ).strip(),
                        tips=sentence_dict.get("tips", "").strip(),
                        lessons=VariantSet(reviewing=ReviewingState()),
                    )
                    entries.append(entry)

                diary_json = upsert_day(diary_json, date_str, title, entries)

            save_diary_json(diary_json, json_path)
            self.logging.info(f"JSON diary updated at {json_path}")
        except Exception as exc:
            self.logging.warning(f"Could not write JSON diary: {exc}")

    def json_diary_to_dict(self):
        """Loads diary entries from diary.json into a structured dictionary.

        Returns:
            dict: Keys are datetime objects, values contain "title" and "sentences" dict.
                  Returns empty dict if json_diary_path is not configured.
        """
        json_path = self.config.get("json_diary_path")
        if not json_path:
            self.logging.warning(
                "json_diary_path not configured; cannot load diary from JSON."
            )
            return {}

        try:
            diary_json = load_diary_json(json_path)
        except Exception as exc:
            self.logging.error(f"Failed to load diary.json: {exc}")
            return {}

        diary_dict = {}
        self.titles_dict = {}

        for day in diary_json.diaries:
            if not day.date:
                continue
            try:
                date_obj = datetime.strptime(day.date, "%Y/%m/%d")
            except ValueError:
                self.logging.warning(
                    f"Invalid date in diary.json: {day.date!r}. Skipping."
                )
                continue

            self.titles_dict[date_obj] = day.title or ""
            sentences = {}
            for i, entry in enumerate(day.entries):
                sentences[i] = {
                    "primary_language_sentence": entry.input_language_sentence or "",
                    "study_language_sentence": entry.output_language_translation or "",
                    "study_language_sentence_trial": entry.user_trial_translation or "",
                    "tips": entry.tips or "",
                }
            diary_dict[date_obj] = {"title": day.title or "", "sentences": sentences}

        return diary_dict

    def diary_complete_translations(self):
        """Completes missing translations in the diary using OpenAI.

        Reads the current diary into a dictionary and iterates through all entries.
        If a study language sentence is missing and automatic translation is enabled
        in the config, it calls OpenAI to generate the translation and tips.
        Finally, writes the updated diary back to the JSON file.
        """
        diary_dict = self.json_diary_to_dict()

        for date_diary, date_dict in diary_dict.items():
            for sentence_no, sentence_dict in date_dict["sentences"].items():
                primary_language_sentence = sentence_dict["primary_language_sentence"]
                if sentence_dict["study_language_sentence"] == "":
                    self.logging.info(
                        f"create missing diary entry with openai for {primary_language_sentence.strip()}"
                    )
                    if self.config.get("create_diary_answers_auto", True):
                        res = self.openai_translate_sentence(sentence_dict)
                        diary_dict[date_diary]["sentences"][sentence_no] = res
                        self.logging.info(
                            f"Translation done for: {primary_language_sentence.strip()[:80]}"
                        )

        self.write_diary_json(diary_dict)


def _build_story_context_block(
    target_sentence: str, all_day_sentences: list | None
) -> str:
    """Return a prompt snippet listing all day sentences as story context.

    When there is only one sentence (or no context), returns an empty string so
    the prompt is unchanged.  The target sentence is marked with '← target' so
    the model knows exactly which sentence to generate Q&A for.
    """
    if not all_day_sentences or len(all_day_sentences) <= 1:
        return ""
    lines = []
    for i, s in enumerate(all_day_sentences, start=1):
        marker = "  ← generate Q&A for this sentence" if s == target_sentence else ""
        lines.append(f"        {i}. {s}{marker}")
    context = "\n".join(lines)
    return (
        f"        ### Full diary entry for context — generate Q&A solely for the sentence marked below:\n"
        f"{context}\n\n"
    )


class TprsVariantHandler:
    def __init__(
        self,
        tprs_creator,
        variant_name: str,
        file_suffix: str,
        openai_method_name: str,
        needs_base_tprs_data: bool = False,
    ):
        """
        Initializes a handler for a specific TPRS variant.

        Args:
            tprs_creator: The parent TprsCreation instance.
            variant_name (str): User-friendly name of the variant (e.g., "Enhanced").
            file_suffix (str): Suffix for filenames (e.g., "_Enhanced").
            openai_method_name (str): Name of the OpenAI method in TprsCreation to generate content.
            needs_base_tprs_data (bool): True if this variant uses existing base TPRS data as input.
        """
        self.tprs_creator = tprs_creator
        self.config = tprs_creator.config  # Get config from parent
        self.logging = tprs_creator.logging  # Get logging from parent
        self.variant_name = variant_name
        self.file_suffix = file_suffix
        self.openai_method_name = openai_method_name
        self.needs_base_tprs_data = needs_base_tprs_data

    def get_openai_generator(self):
        """Returns the appropriate OpenAI content generation method from TprsCreation."""
        return getattr(self.tprs_creator, self.openai_method_name)

    def create_initial_if_needed(self, diary_dict, base_tprs_dict=None):
        """Creates initial TPRS content for this variant in diary.json if not yet populated."""
        existing_data = self._read_variant_tprs_from_json()
        if not existing_data:
            self.logging.info(
                f"No existing {self.variant_name} TPRS data found in diary.json. Generating initial content."
            )
            self._generate_json_content(diary_dict, base_tprs_dict)
        else:
            self.logging.info(
                f"{self.variant_name} TPRS data already exists in diary.json. Skipping initial creation."
            )

    def _generate_json_content(self, diary_dict, base_tprs_dict=None):
        """Generates TPRS content for diary entries and writes to diary.json."""
        output_dict = {}
        openai_func = self.get_openai_generator()

        for diary_date, date_entry in diary_dict.items():
            day_qa_dict = {}

            # Collect all non-empty sentences for the day to use as story context.
            all_day_sentences = [
                sd["study_language_sentence"]
                for sd in date_entry["sentences"].values()
                if sd.get("study_language_sentence")
            ]

            for sentence_no, sentence_dict in date_entry["sentences"].items():
                sentence = sentence_dict["study_language_sentence"]
                if not sentence:
                    self.logging.warning(
                        f"Skipping empty study language sentence for {diary_date}, entry {sentence_no} in {self.variant_name} TPRS generation."
                    )
                    continue

                self.logging.info(
                    f'Creating {self.variant_name} TPRS content for "{sentence}"'
                )

                try:
                    if self.needs_base_tprs_data:
                        if (
                            not base_tprs_dict
                            or diary_date not in base_tprs_dict
                            or sentence not in base_tprs_dict.get(diary_date, {})
                        ):
                            self.logging.warning(
                                f"Missing base TPRS data for {self.variant_name} variant, sentence: '{sentence}' on {diary_date}. Skipping."
                            )
                            continue
                        existing_qa = base_tprs_dict[diary_date][sentence]
                        qa_dict_or_block = openai_func(
                            sentence, existing_qa, all_day_sentences=all_day_sentences
                        )
                    else:
                        qa_dict_or_block = openai_func(
                            sentence, all_day_sentences=all_day_sentences
                        )

                    if self.needs_base_tprs_data:
                        # openai_tprs_enhanced/future/present() returns
                        # {revised_sentence: {qa}}.  The revised sentence is
                        # NOT a valid key for _write_json_tprs (which matches
                        # by output_language_translation).  Extract the Q&A
                        # values and store under the original sentence key.
                        qa_data = next(iter(qa_dict_or_block.values()), {})
                        day_qa_dict[sentence] = qa_data
                    else:
                        day_qa_dict[sentence] = qa_dict_or_block

                    self.logging.info(
                        json.dumps(qa_dict_or_block, indent=2, ensure_ascii=False)
                    )
                except Exception as e:
                    self.logging.error(
                        f"Error generating {self.variant_name} TPRS for sentence '{sentence}': {e}",
                        exc_info=True,
                    )
                    continue

            if day_qa_dict:
                output_dict[diary_date] = day_qa_dict

        if any(output_dict.values()):
            sorted_output_dict = dict(sorted(output_dict.items()))
            self.write_json_tprs(sorted_output_dict)
        else:
            self.logging.info(
                f"No TPRS content generated for {self.variant_name} variant. JSON not updated."
            )

    def write_json_tprs(self, tprs_variant_dict):
        """Writes the TPRS dictionary for this variant to diary.json."""
        self._write_json_tprs(tprs_variant_dict)

    def _write_json_tprs(self, tprs_variant_dict):
        """Update the JSON diary file with Q&A data for this TPRS variant.

        Matches entries by output_language_translation text.
        Silently skips if json_diary_path is not configured.
        """
        json_path = self.config.get("json_diary_path")
        if not json_path:
            return

        json_key = VARIANT_NAME_MAP.get(self.variant_name)
        if json_key is None:
            return

        try:
            diary_json = load_diary_json(json_path)

            for date_obj, sentence_dict_for_day in tprs_variant_dict.items():
                date_str = date_obj.strftime("%Y/%m/%d")
                day = next((d for d in diary_json.diaries if d.date == date_str), None)
                if day is None:
                    continue

                for sentence_text, qa_raw in sentence_dict_for_day.items():
                    # Match entry by output_language_translation
                    matched_entry = None
                    for entry in day.entries:
                        if (
                            entry.output_language_translation.strip()
                            == sentence_text.strip()
                        ):
                            matched_entry = entry
                            break
                    if matched_entry is None:
                        continue

                    # Build a lookup of existing QA for this variant so we can
                    # preserve question_input/answer_input and audio fields that
                    # were written by the backfill step and must not be overwritten.
                    existing_qa_by_index: dict = {}
                    existing_variant = getattr(matched_entry.lessons, json_key, None)
                    if existing_variant is not None:
                        for i, existing_qa in enumerate(existing_variant.qa):
                            existing_qa_by_index[i] = existing_qa

                    qa_list = []
                    for i, k in enumerate(
                        sorted(
                            qa_raw.keys(),
                            key=lambda x: int(x) if x.isdigit() else 0,
                        )
                    ):
                        existing = existing_qa_by_index.get(i)
                        qa_list.append(
                            QA(
                                question=qa_raw[k]["question"],
                                answer=qa_raw[k]["answer"],
                                # Preserve already-populated fields — never blank them out
                                question_input=(
                                    existing.question_input
                                    if existing and existing.question_input
                                    else ""
                                ),
                                answer_input=(
                                    existing.answer_input
                                    if existing and existing.answer_input
                                    else ""
                                ),
                                question_timing=(
                                    existing.question_timing
                                    if existing
                                    else AudioTiming()
                                ),
                                answer_timing=(
                                    existing.answer_timing
                                    if existing
                                    else AudioTiming()
                                ),
                                question_audio_path=(
                                    existing.question_audio_path if existing else ""
                                ),
                                answer_audio_path=(
                                    existing.answer_audio_path if existing else ""
                                ),
                            )
                        )
                    existing_sl = getattr(matched_entry.lessons, json_key, None)
                    matched_entry.lessons.set_variant(
                        json_key,
                        SentenceBlock(
                            sentence=sentence_text,
                            qa=qa_list,
                            # Preserve sentence-level fields written by other steps
                            sentence_input=(
                                existing_sl.sentence_input
                                if existing_sl and existing_sl.sentence_input
                                else ""
                            ),
                            audio_timing=(
                                existing_sl.audio_timing
                                if existing_sl
                                else AudioTiming()
                            ),
                            sentence_audio_path=(
                                existing_sl.sentence_audio_path if existing_sl else ""
                            ),
                            sentence_audio_generated_at=(
                                existing_sl.sentence_audio_generated_at
                                if existing_sl
                                else None
                            ),
                        ),
                    )

            save_diary_json(diary_json, json_path)
            self.logging.info(
                f"JSON diary updated with {self.variant_name} TPRS data at {json_path}"
            )
        except Exception as exc:
            self.logging.warning(
                f"Could not write {self.variant_name} TPRS data to JSON diary: {exc}"
            )

    def _read_variant_tprs_from_json(self):
        """Reads this variant's TPRS Q&A data from diary.json into a structured dictionary.

        Returns a dict keyed by datetime: {datetime_obj: {sentence_text: {"1": {"question": ..., "answer": ...}, ...}}}
        """
        json_path = self.tprs_creator.config.get("json_diary_path")
        if not json_path:
            self.logging.warning(
                "json_diary_path not configured; cannot read TPRS from JSON."
            )
            return {}

        json_key = VARIANT_NAME_MAP.get(self.variant_name)
        if json_key is None:
            return {}

        try:
            diary_json = load_diary_json(json_path)
        except Exception as exc:
            self.logging.error(f"Failed to load diary.json for TPRS read: {exc}")
            return {}

        variant_tprs_dict = {}
        for day in diary_json.diaries:
            if not day.date:
                continue
            try:
                date_obj = datetime.strptime(day.date, "%Y/%m/%d")
            except ValueError:
                continue

            day_output_dict = {}
            for entry in day.entries:
                sentence_text = entry.output_language_translation
                if not sentence_text:
                    continue
                variant_lesson = entry.lessons.get_variant(json_key)
                if not variant_lesson.qa:
                    continue
                qa_map = {
                    str(i + 1): {"question": qa.question, "answer": qa.answer}
                    for i, qa in enumerate(variant_lesson.qa)
                }
                day_output_dict[sentence_text] = qa_map

            if day_output_dict:
                variant_tprs_dict[date_obj] = day_output_dict

        return variant_tprs_dict

    def add_missing_entries(self, diary_dict, base_tprs_dict=None):
        """Adds missing TPRS entries for this variant based on the diary."""
        variant_tprs_content_dict = self._read_variant_tprs_from_json()
        if variant_tprs_content_dict is None:  # Should be {} if file doesn't exist
            variant_tprs_content_dict = {}

        openai_func = self.get_openai_generator()
        updated = False
        updated_dates: set = set()  # tracks dates where new Q&A was generated

        if (
            not hasattr(self.tprs_creator, "titles_diary_dict")
            or not self.tprs_creator.titles_diary_dict
        ):
            self.tprs_creator.get_all_diary_titles()

        for diary_date, date_entry in diary_dict.items():
            # Ensure diary_date is a datetime object for comparison and dictionary key
            if isinstance(diary_date, str):
                try:
                    # Ensure conversion to datetime.datetime if it's a string
                    diary_date = datetime.strptime(diary_date, "%Y-%m-%d")
                except ValueError:
                    try:
                        diary_date = datetime.strptime(diary_date, "%Y/%m/%d")
                    except ValueError:
                        self.logging.error(
                            f"Invalid date format '{diary_date}' from diary_dict. Skipping."
                        )
                        continue

            # diary_date is datetime.datetime (from diary_dict or parsed string)
            # variant_tprs_content_dict and base_tprs_dict are keyed by datetime.datetime.
            # So, use diary_date directly as diary_date_key.
            diary_date_key = diary_date

            # Ensure the date entry exists in the variant's content dictionary
            if diary_date_key not in variant_tprs_content_dict:
                variant_tprs_content_dict[diary_date_key] = {}

            current_day_variant_content = variant_tprs_content_dict[diary_date_key]

            for sentence_no, sentence_details in date_entry.get(
                "sentences", {}
            ).items():
                diary_sentence_text = sentence_details.get("study_language_sentence")
                if not diary_sentence_text:
                    continue

                # Determine if this sentence needs processing for this variant
                needs_processing = False
                if self.variant_name == "Standard":
                    if diary_sentence_text not in current_day_variant_content:
                        needs_processing = True
                else:  # For 'Enhanced', 'Future', 'Present'
                    # Check at the sentence level: a sentence is missing if the base
                    # Standard TPRS sentence is not yet present in this variant's content
                    # for this date. This handles both brand-new dates AND new sentences
                    # added to an existing date.
                    if diary_sentence_text not in current_day_variant_content:
                        needs_processing = True

                if needs_processing:
                    self.logging.info(
                        f"Missing/New {self.variant_name} TPRS for '{diary_sentence_text}' on {diary_date_key}. Generating."
                    )
                    updated = True

                    try:
                        if self.needs_base_tprs_data:
                            if (
                                not base_tprs_dict
                                or diary_date_key not in base_tprs_dict
                                or diary_sentence_text
                                not in base_tprs_dict.get(diary_date_key, {})
                            ):
                                self.logging.warning(
                                    f"Missing base TPRS data for {self.variant_name} variant, sentence: '{diary_sentence_text}' on {diary_date_key} during add_missing. Skipping."
                                )
                                continue
                            existing_qa_for_sentence = base_tprs_dict[diary_date_key][
                                diary_sentence_text
                            ]
                            qa_block = openai_func(
                                diary_sentence_text, existing_qa_for_sentence
                            )
                            # openai_tprs_enhanced/future/present() returns
                            # {revised_sentence: {qa}}.  The revised sentence
                            # is NOT a valid lookup key for _write_json_tprs
                            # (which matches by output_language_translation).
                            # Extract the Q&A values and store under the
                            # original sentence key instead.
                            qa_data = next(iter(qa_block.values()), {})
                            current_day_variant_content[diary_sentence_text] = qa_data
                            date_str = diary_date_key.strftime("%Y/%m/%d")
                            updated_dates.add(date_str)
                        else:  # Standard TPRS
                            qa_data = openai_func(diary_sentence_text)
                            current_day_variant_content[diary_sentence_text] = qa_data
                        self.logging.info(
                            f"{self.variant_name} TPRS: Generated Q&A for '{diary_sentence_text[:60]}' on {diary_date_key}."
                        )
                    except Exception as e:
                        self.logging.error(
                            f"Error generating {self.variant_name} TPRS for sentence '{diary_sentence_text}' during add_missing: {e}",
                            exc_info=True,
                        )
                        continue  # Skip this sentence

        sorted_tprs_variant_dict = dict(sorted(variant_tprs_content_dict.items()))
        if updated:
            self.logging.info(
                f"{self.variant_name} TPRS: writing updated Q&A to diary.json."
            )
            self.write_json_tprs(sorted_tprs_variant_dict)
            # Clear this variant's audio path for any dates that received new Q&A
            # so convert_to_audio() regenerates audio (avoids keeping stale/partial MP3s).
            if updated_dates:
                self._clear_variant_audio_paths(updated_dates)
        else:
            self.logging.info(
                f"{self.variant_name} TPRS: all sentences already present — nothing to generate."
            )

    def _clear_variant_audio_paths(self, date_strs: set):
        """Clear this variant's audio path for the given dates so audio is regenerated."""
        variant_key = VARIANT_AUDIO_KEY_MAP.get(
            self.variant_name, self.variant_name.lower()
        )
        json_path = self.tprs_creator.config.get("json_diary_path")
        if not json_path:
            return
        try:
            diary_db = load_diary_json(json_path)
            changed = False
            for date_str in date_strs:
                day = get_day(diary_db, date_str)
                if day and variant_key in day.lesson_audio_paths:
                    del day.lesson_audio_paths[variant_key]
                    changed = True
                    self.logging.info(
                        f"Cleared stale {self.variant_name} audio path for {date_str} — will regenerate."
                    )
            if changed:
                save_diary_json(diary_db, json_path)
        except Exception as exc:
            self.logging.warning(
                f"Could not clear {self.variant_name} audio paths: {exc}"
            )


class StandardTprsVariantHandler(TprsVariantHandler):
    def __init__(self, tprs_creator):
        super().__init__(
            tprs_creator,
            variant_name="Standard",
            file_suffix="",  # No suffix for standard TPRS files
            openai_method_name="openai_tprs",
            needs_base_tprs_data=False,
        )


class EnhancedTprsVariantHandler(TprsVariantHandler):
    def __init__(self, tprs_creator):
        super().__init__(
            tprs_creator,
            variant_name="Enhanced",
            file_suffix="_enhanced",
            openai_method_name="openai_tprs_enhanced",
            needs_base_tprs_data=True,
        )


class FutureTprsVariantHandler(TprsVariantHandler):
    def __init__(self, tprs_creator):
        super().__init__(
            tprs_creator,
            variant_name="Future",
            file_suffix="_future",
            openai_method_name="openai_tprs_future",
            needs_base_tprs_data=True,
        )


class PresentTprsVariantHandler(TprsVariantHandler):
    def __init__(self, tprs_creator):
        super().__init__(
            tprs_creator,
            variant_name="Present",
            file_suffix="_present",
            openai_method_name="openai_tprs_present",
            needs_base_tprs_data=True,
        )


class TprsCreation(DiaryHandler):
    def __init__(self, config_path=None):
        """Initializes the TprsCreation class, inheriting from DiaryHandler.

        Sets up TPRS variant handlers, ensures initial markdown files are created
        or updated based on the diary and base TPRS content.

        Args:
            config_path (str, optional): Path to the configuration file.
                                         Defaults to None.
        """
        super().__init__(config_path)

        self.variants = [
            StandardTprsVariantHandler(self),
            EnhancedTprsVariantHandler(self),
            FutureTprsVariantHandler(self),
            PresentTprsVariantHandler(self),
        ]

        # Load diary data from JSON
        diary_dict = self.json_diary_to_dict()

        # --- Standard TPRS Handling ---
        standard_variant = self.variants[0]
        if not isinstance(standard_variant, StandardTprsVariantHandler):
            self.logging.critical(
                "StandardTprsVariantHandler not found as first variant. Aborting TPRS setup."
            )
            raise ValueError("StandardTprsVariantHandler configuration error.")

        # Ensure standard TPRS content exists (creates if missing, skips if present)
        standard_variant.create_initial_if_needed(diary_dict)

        # Update standard TPRS: add new sentences from diary that are missing in JSON
        self.check_missing_sentences_from_existing_tprs()

        # Read the (potentially updated) standard TPRS data for use as base for other variants
        base_tprs_dict = standard_variant._read_variant_tprs_from_json()
        if not base_tprs_dict and any(
            v.needs_base_tprs_data for v in self.variants[1:]
        ):
            self.logging.warning(
                "Standard TPRS data is empty, but other variants need it. They might not generate correctly."
            )

        # --- Other Variants Handling ---
        for variant in self.variants:
            if variant.variant_name == "Standard":
                variant.create_initial_if_needed(diary_dict)
            else:
                variant.create_initial_if_needed(diary_dict, base_tprs_dict)

        # Ensure TPRS output directory exists (for audio files)
        os.makedirs(os.path.join(self.output_dir, "TPRS"), exist_ok=True)

        self.get_all_tprs_titles()
        self.get_all_diary_titles()

    def get_all_tprs_titles(self):
        """Loads TPRS titles from diary.json into self.titles_dict."""
        self.titles_dict = {}
        json_path = self.config.get("json_diary_path")
        if not json_path:
            return

        try:
            diary_json = load_diary_json(json_path)
            for day in diary_json.diaries:
                if day.date and day.title:
                    try:
                        date_obj = datetime.strptime(day.date, "%Y/%m/%d")
                        self.titles_dict[date_obj] = day.title
                    except ValueError:
                        pass
        except Exception as exc:
            self.logging.warning(f"Could not load TPRS titles from diary.json: {exc}")

    def _clear_lesson_audio_path_for_date(self, date_str: str):
        """Clear the lesson_audio_path for all variants on a date so audio is regenerated."""
        json_path = self.config.get("json_diary_path")
        if not json_path:
            return
        try:
            diary_db = load_diary_json(json_path)
            day = get_day(diary_db, date_str)
            if day:
                day.lesson_audio_paths.clear()
                save_diary_json(diary_db, json_path)
                self.logging.info(
                    f"Cleared lesson_audio_paths for {date_str} — audio will be regenerated."
                )
        except Exception as exc:
            self.logging.warning(
                f"Could not clear lesson_audio_paths for {date_str}: {exc}"
            )

    def get_all_diary_titles(self):
        """Loads diary titles from diary.json into self.titles_diary_dict."""
        self.titles_diary_dict = {}
        json_path = self.config.get("json_diary_path")
        if not json_path:
            return

        try:
            diary_json = load_diary_json(json_path)
            for day in diary_json.diaries:
                if day.date and day.title:
                    try:
                        date_obj = datetime.strptime(day.date, "%Y/%m/%d")
                        self.titles_diary_dict[date_obj] = day.title
                    except ValueError:
                        pass
        except Exception as exc:
            self.logging.warning(f"Could not load diary titles from diary.json: {exc}")

    def openai_tprs_enhanced(
        self, study_language_sentence, qa_org_dict, all_day_sentences=None
    ):
        """Generates an enhanced TPRS teaching block using OpenAI.

        Rewrites a given sentence and its original Q&A block for better clarity,
        fluency, and TTS compatibility.

        Args:
            study_language_sentence (str): The original sentence in the study language.
            qa_org_dict (dict): The original TPRS question and answer dictionary
                                for the sentence.
            all_day_sentences (list[str] | None): All sentences for the diary day, used
                                                  as story context.

        Returns:
            dict: A new TPRS Q&A dictionary where the key is the revised sentence
                  and the value is a dictionary of new circling-style questions and answers.
        """
        story_context_block = _build_story_context_block(
            study_language_sentence, all_day_sentences
        )
        # study_language_sentence = next(iter(qa_org_dict))
        prompt = f"""
        You are an expert in language teaching using the TPRS (Teaching Proficiency through Reading and Storytelling) method.

        Your task is to rewrite a {self.config["languages"]["study_language"]} teaching block using the TPRS method, enhancing it for clarity and spoken fluency with Text-to-Speech (TTS).

        I will give you a teaching block in {self.config["languages"]["study_language"]} that contains:
        - the main key is One or more narrative sentences,
        - containing a sub-json dictionary: A set of comprehension questions and answers, formatted as a Python dictionary like this:
        {{
            "1": {{"question": "Hva skjedde med Johanne på fredag?", "answer": "Johanne var veldig syk."}},
            "2": {{"question": "Hva gjorde vi etter at Johanne var syk?", "answer": "Vi ble hjemme og senere dro vi for å fiske med Emil og Mati."}},
            "3": {{"question": "Hvem var de vi dro for å fiske med?", "answer": "Vi dro for å fiske med Emil og Mati."}},
            "4": {{"question": "Hva var spesielt med fisken jeg fanget?", "answer": "Det var min første norske fisk."}}
        }}

{story_context_block}
        Follow these guidelines:
        - Generate a revised version of the input sentence: "{study_language_sentence}".
        - Vary the wording slightly for fluency and naturalness.
        - After revising the sentence, generate circling-style questions (yes/no, either/or, open-ended) that cover all key information.
        - Use natural, beginner-friendly language.
        - Add brief synonym explanations or rewordings only if they help understanding.
        - Do not omit any details. Expand abbreviations into natural spoken forms for TTS output in {self.config["languages"]["study_language"]}.
        - Output in {self.config["languages"]["study_language"]} only.
        - Ensure the final output is a single valid JSON object.
        - The **key** must be the revised sentence as a natural language string in {self.config["languages"]["study_language"]}.
        - The **value** must be a dictionary of circling-style questions and answers, where keys are strings of integers starting from "1".
        - Use the {self.config["languages"]["output_script"]} script for all generated text in {self.config["languages"]["study_language"]}.

        For example:

        {{
        "Neste morgen, på søndag, var havet helt stille – det glitret som et speil, og det lå lave skyer over det.": {{
            "1": {{"question": "Var det søndag eller mandag morgen?", "answer": "Det var søndag morgen."}},
            "2": {{"question": "Hvordan så havet ut?", "answer": "Det så ut som et speil."}}
        }}
        }}

        Do **not** use keys like "key" or "value". Only use the revised sentence itself as the top-level key.

        Do **not** use placeholder strings like "REVISED SENTENCE".

        Now generate logical questions and answers in {self.config["languages"]["study_language"]} for the following sentence:
        - "{study_language_sentence}"

        Here is the existing Question and Answer block:
        {qa_org_dict}
        """

        self.logging.info(
            f"[OpenAI] Enhanced TPRS for: {study_language_sentence[:80].strip()}..."
        )
        qa_dict = json.loads(
            self._openai_call([{"role": "user", "content": prompt}], json_mode=True)
        )
        self.logging.info(f"[OpenAI] Enhanced TPRS done ({len(qa_dict)} Q&A pairs).")
        return qa_dict

    def openai_tprs_future(
        self, study_language_sentence, qa_org_dict, all_day_sentences=None
    ):
        """Generates a future tense TPRS teaching block using OpenAI.

        Transforms a given sentence and its original Q&A block into the future tense,
        enhancing it for clarity, fluency, and TTS compatibility.

        Args:
            study_language_sentence (str): The original sentence in the study language.
            qa_org_dict (dict): The original TPRS question and answer dictionary
                                for the sentence.
            all_day_sentences (list[str] | None): All sentences for the diary day, used
                                                  as story context.

        Returns:
            dict: A new TPRS Q&A dictionary where the key is the revised sentence
                  (in future tense) and the value is a dictionary of new, future-oriented
                  circling-style questions and answers.
        """
        story_context_block = _build_story_context_block(
            study_language_sentence, all_day_sentences
        )
        prompt = f"""
        You are an expert in language teaching using the TPRS (Teaching Proficiency through Reading and Storytelling) method.

        Your task is to rewrite a {self.config["languages"]["study_language"]} teaching block using the TPRS method, transforming it into the **future tense** for clarity and spoken fluency with Text-to-Speech (TTS).

        I will give you a teaching block in {self.config["languages"]["study_language"]} that contains:
        - the main key is one or more narrative sentences,
        - containing a sub-json dictionary: a set of comprehension questions and answers, formatted as a Python dictionary like this:
        {{
            "1": {{"question": "Hva skjedde med Johanne på fredag?", "answer": "Johanne var veldig syk."}},
            "2": {{"question": "Hva gjorde vi etter at Johanne var syk?", "answer": "Vi ble hjemme og senere dro vi for å fiske med Emil og Mati."}}
        }}

{story_context_block}
        Follow these guidelines:
        - Convert the input sentence "{study_language_sentence}" to future tense, as it would be spoken naturally in {self.config["languages"]["study_language"]}.
        - Vary the wording slightly to ensure fluency and naturalness.
        - After revising the sentence, generate circling-style questions (yes/no, either/or, open-ended) that reflect the new future-oriented sentence.
        - Use beginner-friendly vocabulary and phrasing.
        - Add brief synonym explanations or rewordings only when helpful for comprehension.
        - Do not omit any factual content. Expand abbreviations into full, natural spoken forms suitable for TTS.
        - Output in {self.config["languages"]["study_language"]} only.
        - Ensure the final output is a single valid JSON object.
        - The **key** must be the revised sentence in future tense, as a natural sentence in {self.config["languages"]["study_language"]}.
        - The **value** must be a dictionary of circling-style questions and answers, with string keys starting from "1".
        - Use the {self.config["languages"]["output_script"]} script for all generated text in {self.config["languages"]["study_language"]}.

        For example:

        {{
        "Neste søndag morgen vil havet være helt stille – det vil glitre som et speil, og det vil være lave skyer over det.": {{
            "1": {{"question": "Vil havet være stille eller stormfullt?", "answer": "Havet vil være stille."}},
            "2": {{"question": "Hvordan vil havet se ut?", "answer": "Det vil glitre som et speil."}}
        }}
        }}

        Do **not** use keys like "key" or "value". Only use the revised sentence itself as the top-level key.

        Do **not** use placeholder strings like "REVISED SENTENCE".

        Now generate logical **future tense** questions and answers in {self.config["languages"]["study_language"]} for the following sentence:
        - "{study_language_sentence}"

        Here is the existing Question and Answer block:
        {qa_org_dict}
        """

        self.logging.info(
            f"[OpenAI] Future TPRS for: {study_language_sentence[:80].strip()}..."
        )
        qa_dict = json.loads(
            self._openai_call([{"role": "user", "content": prompt}], json_mode=True)
        )
        self.logging.info(f"[OpenAI] Future TPRS done ({len(qa_dict)} Q&A pairs).")
        return qa_dict

    def openai_tprs_present(
        self, study_language_sentence, qa_org_dict, all_day_sentences=None
    ):
        """Generates a present tense TPRS teaching block using OpenAI.

        Transforms a given sentence and its original Q&A block into the present tense,
        enhancing it for clarity, fluency, and TTS compatibility.

        Args:
            study_language_sentence (str): The original sentence in the study language.
            qa_org_dict (dict): The original TPRS question and answer dictionary
                                for the sentence.
            all_day_sentences (list[str] | None): All sentences for the diary day, used
                                                  as story context.

        Returns:
            dict: A new TPRS Q&A dictionary where the key is the revised sentence
                  (in present tense) and the value is a dictionary of new, present-oriented
                  circling-style questions and answers.
        """
        story_context_block = _build_story_context_block(
            study_language_sentence, all_day_sentences
        )
        prompt = f"""
        You are an expert in language teaching using the TPRS (Teaching Proficiency through Reading and Storytelling) method.

        Your task is to rewrite a {self.config["languages"]["study_language"]} teaching block using the TPRS method, transforming it into the **present tense** for clarity and spoken fluency with Text-to-Speech (TTS).

        I will give you a teaching block in {self.config["languages"]["study_language"]} that contains:
        - the main key is one or more narrative sentences,
        - containing a sub-json dictionary: a set of comprehension questions and answers, formatted as a Python dictionary like this:
        {{
            "1": {{"question": "Hva skjer med Johanne på fredag?", "answer": "Johanne er veldig syk."}},
            "2": {{"question": "Hva gjør vi etter at Johanne er syk?", "answer": "Vi blir hjemme og senere drar vi for å fiske med Emil og Mati."}}
        }}

{story_context_block}
        Follow these guidelines:
        - Convert the input sentence "{study_language_sentence}" to **present tense**, as it would be spoken naturally in {self.config["languages"]["study_language"]}.
        - Vary the wording slightly to ensure fluency and naturalness.
        - After revising the sentence, generate circling-style questions (yes/no, either/or, open-ended) that reflect the new **present-tense** sentence.
        - Use beginner-friendly vocabulary and phrasing.
        - Add brief synonym explanations or rewordings only when helpful for comprehension.
        - Do not omit any factual content. Expand abbreviations into full, natural spoken forms suitable for TTS.
        - Output in {self.config["languages"]["study_language"]} only.
        - Ensure the final output is a single valid JSON object.
        - The **key** must be the revised sentence in present tense, as a natural sentence in {self.config["languages"]["study_language"]}.
        - The **value** must be a dictionary of circling-style questions and answers, with string keys starting from "1".
        - Use the {self.config["languages"]["output_script"]} script for all generated text in {self.config["languages"]["study_language"]}.

        For example:

        {{
        "Nå på søndag morgen er havet helt stille – det glitrer som et speil, og det er lave skyer over det.": {{
            "1": {{"question": "Er havet stille eller stormfullt?", "answer": "Havet er stille."}},
            "2": {{"question": "Hvordan ser havet ut?", "answer": "Det glitrer som et speil."}}
        }}
        }}

        Do **not** use keys like "key" or "value". Only use the revised sentence itself as the top-level key.

        Do **not** use placeholder strings like "REVISED SENTENCE".

        Now generate logical **present tense** questions and answers in {self.config["languages"]["study_language"]} for the following sentence:
        - "{study_language_sentence}"

        Here is the existing Question and Answer block:
        {qa_org_dict}
        """

        self.logging.info(
            f"[OpenAI] Present TPRS for: {study_language_sentence[:80].strip()}..."
        )
        qa_dict = json.loads(
            self._openai_call([{"role": "user", "content": prompt}], json_mode=True)
        )
        self.logging.info(f"[OpenAI] Present TPRS done ({len(qa_dict)} Q&A pairs).")
        return qa_dict

    def openai_tprs(self, study_language_sentence, all_day_sentences=None):
        """Generates TPRS questions and answers for a given sentence using OpenAI.

        The generated Q&A aims to be natural, logically sound, and suitable for TTS.
        It considers the emotional tone and style of the input sentence.

        Args:
            study_language_sentence (str): The sentence in the study language for which
                                           to generate TPRS content.
            all_day_sentences (list[str] | None): All sentences for the diary day, used
                                                  as story context so pronouns and
                                                  references resolve correctly.

        Returns:
            dict: A dictionary where keys are numbers (as strings, starting from "1")
                  and values are dictionaries, each containing a "question" and "answer".
        """
        story_context_block = _build_story_context_block(
            study_language_sentence, all_day_sentences
        )

        prompt = f"""
        We are working on a TPRS (Teaching Proficiency through Reading and Storytelling) method to learn {
            self.config["languages"]["study_language"]
        }.
        All output must be written in {self.config["languages"]["study_language"]}.
{story_context_block}        Generate a set of questions and answers for the target sentence in {
            self.config["languages"]["study_language"]
        }.
        The output should be a JSON dictionary where:
        - The main keys are numbers (starting from 1) as strings.
        - Each value is another dictionary with two keys: "question" and "answer".
        - **DO NOT invent extra words or modify the original meaning of the sentence.**
        - **Preserve unusual or idiomatic expressions exactly as they appear.**
        - **Questions must be logically sound and relevant to the sentence.**
        - **Make sure the questions and answers sound natural, like a native speaker would actually say them.**
        - Ensure that the **answers are complete, not just one-word replies.**
        - **Avoid overly formal, awkward, or robotic phrases.**
        - Each question should be directly answerable from the sentence, but not repetitive.
        - don't use emojis as this will be converted for TTS
        - The original sentence may include informal, emotional, or sexual language. Do not censor or sanitise it.
        - Interpret the sentence like a native speaker would, even if the content is suggestive or mature.
        - **Questions should explore various aspects of the sentence (who, what, when, how, why), without repeating the same information.**
        - **Try to match the emotional tone or style of the sentence (e.g., casual, funny, dramatic).**
        - **Avoid repeating the same phrasing or vocabulary in both the questions and answers. Use different angles, emotions, or contextual clues to make each question unique.**
        - **You can explore the setting, emotional dynamics, or deeper meanings behind the actions in the sentence.**
        - Generate a sentence that is ready to be spoken by a Text-to-Speech system. Expand abbreviations that are not normally spoken as-is (e.g., 'km/h' should become 'kilometers per hour'), but keep common spoken abbreviations (e.g., 'AM', 'PM') unchanged. Ensure the result is natural for TTS. Adapt abbreviation expansion appropriately to the target language {
            self.config["languages"]["study_language"]
        }.
        - In addition, when generating text for non-English languages, expand non-spoken abbreviations according to natural usage in that language (e.g., in French, 'km/h' ➔ 'kilomètres par heure').
        - Use the {
            self.config["languages"]["output_script"]
        } script for all generated text in {self.config["languages"]["study_language"]}.

         ### Example 1 – Neutral:
        Input sentence: "Fredag var Johanne veldig syk. Vi ble hjemme og dro for å fiske med Emil og Mati. Jeg var den første som fanget noe – min første norske fisk."

        Expected questions and answers:
        {{
            "1": {{"question": "Hva skjedde med Johanne på fredag?", "answer": "Johanne var veldig syk."}},
            "2": {{"question": "Hva gjorde vi etter at Johanne var syk?", "answer": "Vi ble hjemme og senere dro vi for å fiske med Emil og Mati."}},
            "3": {{"question": "Hvem var de vi dro for å fiske med?", "answer": "Vi dro for å fiske med Emil og Mati."}},
            "4": {{"question": "Hva var spesielt med fisken jeg fanget?", "answer": "Det var min første norske fisk."}}
        }}

        ### Example 2 – Sad:
        Input sentence: "Elle est partie sans dire au revoir. Je suis resté seul avec mon café froid."

        Expected questions and answers:
        {{
            "1": {{"question": "Pourquoi est-ce que tu es resté seul ?", "answer": "Parce qu'elle est partie sans dire au revoir."}},
            "2": {{"question": "Qu'est-ce qu'elle a oublié de faire en partant ?", "answer": "Elle n'a pas dit au revoir."}},
            "3": {{"question": "Avec quoi es-tu resté après son départ ?", "answer": "Avec mon café froid... et ma solitude."}}
        }}

        ### Example 3 – Funny:
        Input sentence: "J'ai mis du sel au lieu du sucre dans mon café. Résultat : je me suis réveillé plus vite que prévu."

        Expected questions and answers:
        {{
            "1": {{"question": "Qu'est-ce que tu as mis dans ton café par erreur ?", "answer": "Du sel au lieu du sucre."}},
            "2": {{"question": "Comment as-tu réagi après avoir bu le café ?", "answer": "Je me suis réveillé plus vite que prévu !"}},
            "3": {{"question": "Pourquoi ton café avait un goût bizarre ?", "answer": "Parce qu’il y avait du sel dedans, pas du sucre."}}
        }}


       ### Example 4 - Cheeky (French):
        Input sentence: "Hier soir, elle est rentrée avec un grand sourire... et sans pantalon."

        Expected questions and answers:
        {{"1": {{"question": "Pourquoi elle avait un grand sourire hier soir ?", "answer": "Parce qu'elle est rentrée sans pantalon."}},
            "2": {{"question": "Comment est-elle rentrée hier soir ?", "answer": "Avec un grand sourire et sans pantalon."}},
            "3": {{"question": "Qu'est-ce qu'il manquait à sa tenue ?", "answer": "Elle n'avait pas de pantalon."}},
            "4": {{"question": "On peut deviner pourquoi elle souriait ?", "answer": "Probablement... mais ce n’est pas écrit dans la phrase."}}
        }}

        ### Now generate logical questions and answers in {
            self.config["languages"]["study_language"]
        } for the target sentence above: "{study_language_sentence}"
        """
        # Make the API call
        self.logging.info(
            f"[OpenAI] Standard TPRS Q&A for: {study_language_sentence[:80].strip()}..."
        )
        qa_dict = json.loads(
            self._openai_call([{"role": "user", "content": prompt}], json_mode=True)
        )
        self.logging.info(f"[OpenAI] Standard TPRS done ({len(qa_dict)} Q&A pairs).")
        return qa_dict

    def openai_translate_qa_batch(self, qa_items: list[dict]) -> list[dict]:
        """Translate a batch of Q&A pairs from study language to primary language.

        Uses a numbered-dict request/response format to avoid fragile array-unwrapping
        with json_object mode.

        Args:
            qa_items: List of dicts with keys ``question`` and ``answer`` (study language).

        Returns:
            List of dicts with keys ``question_input`` and ``answer_input``
            (primary language), in the same order as ``qa_items``.
            Returns an empty list on failure.
        """
        primary = self.config["languages"]["primary_language"]
        study = self.config["languages"]["study_language"]
        numbered_input = {str(i + 1): item for i, item in enumerate(qa_items)}

        prompt = (
            f"You are a translator. Translate each Q&A pair from {study} into {primary}.\n\n"
            f"Input is a JSON object where each key is a number and each value has "
            f'"question" and "answer" fields in {study}.\n\n'
            f"Return a JSON object with the same numbered keys, each value having:\n"
            f'- "question_input": the question translated into {primary}\n'
            f'- "answer_input": the answer translated into {primary}\n\n'
            f"Rules:\n"
            f"- Preserve meaning exactly; do not add or remove content.\n"
            f"- Keep the same natural, spoken tone as the original.\n"
            f"- Use the same numbered keys as the input.\n\n"
            f"### Example\n"
            f'Input: {{"1": {{"question": "Hvem var der?", "answer": "Vi var der."}}, '
            f'"2": {{"question": "Hva skjedde?", "answer": "Vi spiste middag."}}}}\n'
            f'Output: {{"1": {{"question_input": "Who was there?", "answer_input": "We were there."}}, '
            f'"2": {{"question_input": "What happened?", "answer_input": "We had dinner."}}}}\n\n'
            f"### Now translate:\n{json.dumps(numbered_input, ensure_ascii=False)}"
        )
        try:
            raw = json.loads(
                self._openai_call(
                    [{"role": "user", "content": prompt}],
                    system="You are a helpful translator.",
                    json_mode=True,
                )
            )
            return [raw[str(i + 1)] for i in range(len(qa_items))]
        except (KeyError, TypeError) as exc:
            self.logging.warning(f"Unexpected translation response shape: {exc}.")
            return []

    def openai_translate_texts_batch(self, texts: list[str]) -> list[str]:
        """Translate a batch of plain-text sentences from study language to primary language.

        Args:
            texts: List of sentences in the study language.

        Returns:
            List of translated sentences in the primary language, same order.
            Returns a list of empty strings on failure.
        """
        primary = self.config["languages"]["primary_language"]
        study = self.config["languages"]["study_language"]
        numbered_input = {str(i + 1): s for i, s in enumerate(texts)}

        prompt = (
            f"You are a translator. Translate each sentence from {study} into {primary}.\n\n"
            f"Input is a JSON object where each key is a number and each value is a sentence in {study}.\n\n"
            f"Return a JSON object with the same numbered keys, each value being the translated sentence in {primary}.\n\n"
            f"Rules:\n"
            f"- Preserve meaning exactly; do not add or remove content.\n"
            f"- Keep the same natural, spoken tone as the original.\n"
            f"- Use the same numbered keys as the input.\n\n"
            f"### Example\n"
            f'Input: {{"1": "Jeg dro til stranden i morges.", "2": "Vi spiste middag klokka åtte."}}\n'
            f'Output: {{"1": "I went to the beach this morning.", "2": "We had dinner at eight."}}\n\n'
            f"### Now translate:\n{json.dumps(numbered_input, ensure_ascii=False)}"
        )
        try:
            raw = json.loads(
                self._openai_call(
                    [{"role": "user", "content": prompt}],
                    system="You are a helpful translator.",
                    json_mode=True,
                )
            )
            return [raw.get(str(i + 1), "") for i in range(len(texts))]
        except (KeyError, TypeError) as exc:
            self.logging.warning(f"Unexpected translation response shape: {exc}.")
            return [""] * len(texts)

    def backfill_qa_translations(self, json_path: str) -> None:
        """Backfill ``question_input``/``answer_input`` for all Q&A pairs missing
        a primary-language translation.

        Safe to call multiple times — already-translated pairs are skipped.
        Saves diary.json after each day that has new translations.
        """
        self.logging.info(f"Starting Q&A translation backfill for {json_path}")
        db = load_diary_json(json_path)
        changed = False
        total_translated = 0

        for day in db.diaries:
            day_changed = False
            day_translated = 0
            for entry in day.entries:
                for variant_name in ("original", "enhanced", "present", "future"):
                    vl = getattr(entry.lessons, variant_name, None)
                    if vl is None or not vl.qa:
                        continue
                    already_done = sum(
                        1 for qa in vl.qa if qa.question_input and qa.answer_input
                    )
                    missing_indices = [
                        j
                        for j, qa in enumerate(vl.qa)
                        if not qa.question_input or not qa.answer_input
                    ]
                    if not missing_indices:
                        continue
                    self.logging.info(
                        f"  [{day.date}] entry {entry.index} {variant_name}: "
                        f"{len(missing_indices)} missing, {already_done} already translated"
                    )
                    qa_items = [
                        {"question": vl.qa[j].question, "answer": vl.qa[j].answer}
                        for j in missing_indices
                    ]
                    try:
                        translations = self.openai_translate_qa_batch(qa_items)
                        written = 0
                        for k, j in enumerate(missing_indices):
                            if k < len(translations):
                                t = translations[k]
                                vl.qa[j].question_input = t.get("question_input", "")
                                vl.qa[j].answer_input = t.get("answer_input", "")
                                if t.get("question_input") and t.get("answer_input"):
                                    written += 1
                        self.logging.info(
                            f"    → wrote {written}/{len(missing_indices)} translations"
                        )
                        day_translated += written
                        day_changed = True
                    except Exception as exc:
                        self.logging.warning(
                            f"  Q&A translation failed for {day.date} entry "
                            f"{entry.index} {variant_name}: {exc}"
                        )

            if day_changed:
                save_diary_json(db, json_path)
                changed = True
                total_translated += day_translated
                self.logging.info(
                    f"  Saved {day_translated} new translations for {day.date}"
                )

        if not changed:
            self.logging.info("Q&A translation backfill: nothing to update.")
        else:
            self.logging.info(
                f"Q&A translation backfill complete — {total_translated} pairs translated."
            )

    def backfill_sentence_inputs(self, json_path: str) -> None:
        """Backfill ``sentence_input`` for variant lessons missing a primary-language
        translation of the variant sentence.

        Skips the ``original`` variant (its sentence is already the study-language
        output; the primary-language equivalent is ``input_language_sentence`` on
        the entry level).  Skips any variant whose ``sentence_input`` is already set.

        Safe to call multiple times.  Saves diary.json after each changed day.
        """
        self.logging.info(f"Starting sentence_input backfill for {json_path}")
        db = load_diary_json(json_path)
        changed = False
        total_translated = 0

        for day in db.diaries:
            day_changed = False
            day_translated = 0
            for entry in day.entries:
                for variant_name in ("enhanced", "present", "future"):
                    vl = getattr(entry.lessons, variant_name, None)
                    if vl is None or not vl.sentence or vl.sentence_input:
                        continue
                    self.logging.info(
                        f"  [{day.date}] entry {entry.index} {variant_name}: "
                        f"translating sentence_input"
                    )
                    try:
                        results = self.openai_translate_texts_batch([vl.sentence])
                        translation = results[0] if results else ""
                        if translation:
                            vl.sentence_input = translation
                            day_translated += 1
                            day_changed = True
                            self.logging.info(f"    → '{translation[:60]}…'")
                        else:
                            self.logging.warning(
                                f"  Empty translation for {day.date} entry "
                                f"{entry.index} {variant_name}"
                            )
                    except Exception as exc:
                        self.logging.warning(
                            f"  sentence_input translation failed for {day.date} "
                            f"entry {entry.index} {variant_name}: {exc}"
                        )

            if day_changed:
                save_diary_json(db, json_path)
                changed = True
                total_translated += day_translated
                self.logging.info(
                    f"  Saved {day_translated} new sentence_input translations for {day.date}"
                )

        if not changed:
            self.logging.info("sentence_input backfill: nothing to update.")
        else:
            self.logging.info(
                f"sentence_input backfill complete — {total_translated} sentences translated."
            )

    def check_missing_sentences_from_existing_tprs(self):
        """
        Checks for sentences in the diary that are missing from the STANDARD TPRS content.
        Updates the standard TPRS file if new sentences are found in the diary.
        This method operates on the StandardTprsVariantHandler's paths and data.
        """
        standard_variant = self.variants[
            0
        ]  # Assumes StandardTprsVariantHandler is the first
        if not isinstance(standard_variant, StandardTprsVariantHandler):
            self.logging.error(
                "StandardTprsVariantHandler not found as first variant. Cannot check missing sentences for standard TPRS."
            )
            return {}  # Return empty dict or handle error as appropriate

        # Read existing standard TPRS content using the variant's method
        tprs_dict = standard_variant._read_variant_tprs_from_json()
        if tprs_dict is None:  # Should be {} if file doesn't exist or is empty
            tprs_dict = {}

        diary_dict = self.json_diary_to_dict()  # From DiaryHandler (parent class)

        if not hasattr(self, "titles_diary_dict") or not self.titles_diary_dict:
            self.get_all_diary_titles()  # Ensure diary titles are loaded for writing

        new_or_updated_tprs_dict_for_standard = tprs_dict.copy()
        made_changes = False

        for date_diary_key, day_entry_in_diary in diary_dict.items():
            # date_diary_key from diary_dict is datetime.datetime
            current_date_key = date_diary_key

            if current_date_key not in new_or_updated_tprs_dict_for_standard:
                new_or_updated_tprs_dict_for_standard[current_date_key] = {}

            current_day_tprs_sentences_data = new_or_updated_tprs_dict_for_standard[
                current_date_key
            ]

            date_changed = False
            for sentence_no, sentence_detail_in_diary in day_entry_in_diary.get(
                "sentences", {}
            ).items():
                study_lang_sentence = sentence_detail_in_diary.get(
                    "study_language_sentence"
                )

                if not study_lang_sentence:
                    primary_lang_sentence = sentence_detail_in_diary.get(
                        "primary_language_sentence", "N/A"
                    )
                    self.logging.debug(
                        f"Skipping empty study language sentence for primary: '{primary_lang_sentence}' on {current_date_key}"
                    )
                    continue

                if study_lang_sentence not in current_day_tprs_sentences_data:
                    self.logging.info(
                        f"Standard TPRS: Missing sentence '{study_lang_sentence}' from diary on {current_date_key}. Generating."
                    )
                    try:
                        # Use the standard variant's OpenAI generator
                        qa_dict_for_sentence = standard_variant.get_openai_generator()(
                            study_lang_sentence
                        )
                        current_day_tprs_sentences_data[
                            study_lang_sentence
                        ] = qa_dict_for_sentence
                        self.logging.info(
                            f"Standard TPRS: Generated Q&A for '{study_lang_sentence[:60]}...' on {current_date_key}."
                        )
                        made_changes = True
                        date_changed = True
                    except Exception as e:
                        self.logging.error(
                            f"Error generating standard TPRS for sentence '{study_lang_sentence}': {e}",
                            exc_info=True,
                        )
                        continue  # Skip this sentence

            if date_changed:
                date_str = (
                    current_date_key.strftime("%Y/%m/%d")
                    if hasattr(current_date_key, "strftime")
                    else current_date_key
                )
                # Clearing the lesson_audio_paths entry ensures the next
                # convert_to_audio run will regenerate audio for this date.
                self._clear_lesson_audio_path_for_date(date_str)

        if made_changes:
            self.logging.info(
                "Updating Standard TPRS in diary.json with newly generated entries from diary."
            )
            sorted_tprs_dict = dict(
                sorted(new_or_updated_tprs_dict_for_standard.items())
            )
            standard_variant.write_json_tprs(sorted_tprs_dict)
        else:
            self.logging.info(
                "No new sentences from diary found missing in Standard TPRS. No changes made by check_missing_sentences_from_existing_tprs."
            )

        return new_or_updated_tprs_dict_for_standard


def main(config_path=None):
    """Main function to run the diary and TPRS processing workflow.

    Args:
        config_path (str, optional): Path to the configuration file.
                                     Defaults to None, which uses the default user config path.

    Initializes DiaryHandler, completes translations.
    Then, initializes TprsCreation, checks for missing TPRS sentences,
    adds missing TPRS content for all versions (standard, enhanced, future, present).
    Audio generation is handled separately via backfill_audio_timings() in the webapp.
    """
    diary_instance = DiaryHandler(config_path=config_path)
    _log = diary_instance.logging  # named logger — goes to output.log
    _log.info("=== Phase 1/2: Diary translations ===")
    diary_instance.diary_complete_translations()
    _log.info("=== Diary translations complete ===")
    diary_instance.stop()

    # --- TPRS Processing ---
    tprs_instance = TprsCreation(config_path=config_path)
    _log = tprs_instance.logging  # re-bind after stop() re-opens handlers
    _log.info("=== Phase 2/2: TPRS Q&A generation ===")

    diary_dict = tprs_instance.json_diary_to_dict()
    if not diary_dict:
        _log.warning(
            "Diary dictionary is empty. TPRS processing might not generate much content."
        )
    else:
        _log.info(f"Loaded {len(diary_dict)} diary day(s) for TPRS processing.")

    standard_variant = tprs_instance.variants[0]
    base_tprs_dict = standard_variant._read_variant_tprs_from_json()
    if not base_tprs_dict and any(
        v.needs_base_tprs_data for v in tprs_instance.variants[1:]
    ):
        _log.warning(
            "Base (Standard) TPRS dictionary is empty. Variants requiring it may not generate correctly."
        )

    for variant in tprs_instance.variants:
        _log.info(
            f"--- Processing TPRS Variant: {variant.variant_name} ({tprs_instance.variants.index(variant)+1}/{len(tprs_instance.variants)}) ---"
        )
        if variant.variant_name == "Standard":
            variant.add_missing_entries(diary_dict)
        else:
            variant.add_missing_entries(diary_dict, base_tprs_dict)
        _log.info(f"Q&A generation done for {variant.variant_name}.")

    tprs_instance.stop()
    _log.info("=== All generation complete ===")
