#!/usr/bin/env python3
"""
Interactive user configuration manager for LingoDiary.

Manage users and their configurations:
  - add-user: Create a new user with interactive prompts
  - modify-user: Update an existing user's configuration
  - delete-user: Remove a user and back up their config

Usage:
    python scripts/manage-config.py [command] [options]

Options:
    -i, --input FILE       Path to docker-compose.yml (default: ../docker-compose.yml)
    -o, --output DIR       Config directory (overrides docker-compose.yml volume)

Examples:
    python scripts/manage-config.py add-user
    python scripts/manage-config.py add-user -o ~/.config/lingoDiary
    python scripts/manage-config.py add-user -i /path/to/docker-compose.yml
"""

import sys
import os
import json
import yaml
import getpass
import tarfile
import argparse
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, Any
from platformdirs import user_config_dir

try:
    import bcrypt
except ImportError:
    print("ERROR: bcrypt is not installed. Install with: pip install bcrypt")
    sys.exit(1)


def resolve_config_dir(
    input_file: Optional[str] = None, output_dir: Optional[str] = None
) -> Path:
    """
    Resolve the configuration directory using the priority:
    1. -o/--output flag (overrides everything)
    2. Parse docker-compose.yml to extract /app/.config/lingoDiary/ volume mount
    3. Fallback to ~/.config/efunk_lingo/lingoDiary/

    Args:
        input_file: Path to docker-compose.yml (from -i flag)
        output_dir: Config directory (from -o flag)

    Returns:
        Path object pointing to the config directory
    """
    # Option 1: -o flag overrides everything
    if output_dir:
        config_dir = Path(output_dir).expanduser()
        return config_dir

    # Option 2: Parse docker-compose.yml
    docker_compose_path = None

    if input_file:
        docker_compose_path = Path(input_file)
    else:
        # Default: look in parent directory of this script
        default_path = Path(__file__).parent.parent / "docker-compose.yml"
        if default_path.exists():
            docker_compose_path = default_path

    if docker_compose_path and docker_compose_path.exists():
        try:
            config_dir = extract_config_from_docker_compose(docker_compose_path)
            if config_dir:
                return config_dir
        except Exception as e:
            print(f"⚠ Could not parse {docker_compose_path}: {e}")

    # Option 3: Fallback
    fallback = Path.home() / ".config" / "efunk_lingo" / "lingoDiary"
    print(f"ℹ Using config directory: {fallback}")
    return fallback


def extract_config_from_docker_compose(compose_path: Path) -> Optional[Path]:
    """
    Extract the host path for /app/.config/lingoDiary/ from docker-compose.yml.

    Example:
        volumes:
          - ~/.config/efunk_lingo/lingoDiary/:/app/.config/lingoDiary/

    Returns:
        Path object pointing to the host directory, or None if not found
    """
    try:
        with open(compose_path, "r") as f:
            compose = yaml.safe_load(f)

        if not compose:
            return None

        # Look for lingo-diary service
        services = compose.get("services", {})
        lingo_service = services.get("lingo-diary", {})
        volumes = lingo_service.get("volumes", [])

        # Find volume entry with /app/.config/lingoDiary/
        for volume_entry in volumes:
            if isinstance(volume_entry, str):
                # Format: "host_path:/container_path" or "named_volume:/container_path"
                if ":/app/.config/lingoDiary/" in volume_entry:
                    host_path = volume_entry.split(":")[0]
                    resolved_path = Path(host_path).expanduser()
                    print(
                        f"ℹ Found config directory in docker-compose.yml: {resolved_path}"
                    )
                    return resolved_path

        return None
    except Exception as e:
        print(f"⚠ Error parsing docker-compose.yml: {e}")
        return None


APP_NAME = "lingoDiary"
CONFIG_DIR = Path(user_config_dir(APP_NAME))
USERS_FILE = CONFIG_DIR / "users.yaml"
BACKUPS_DIR = CONFIG_DIR / "backups"
VOICES_FILE = Path(__file__).parent / "piper_voices.yaml"

# Default config template
DEFAULT_CONFIG_TEMPLATE = """# LingoDiary User Configuration
# Generated by manage-config.py

output_dir: "/data/{username}/"

# Diary processing
diary_entries_prompt_user: true
overwrite_diary_markdown: true
overwrite_tprs_markdown: true
overwrite_tprs_audio: false

# Content generation
create_tprs_auto: true
create_diary_answers_auto: true
create_anki_deck: false

# OpenAI Configuration
openai:
  key: "{openai_key}"
  model: "gpt-4o-mini"

# Grammar output
gender: "{gender}"

# Languages
languages:
  primary_language: "{primary_language}"
  primary_language_code: "{primary_language_code}"
  study_language: "{study_language}"
  study_language_code: "{study_language_code}"

# Text-to-Speech (Piper)
tts:
  model: "piper"
  piper:
    piper_length_scale_diary: 2
    piper_length_scale_tprs: 2
    voice: "{study_voice}"
  piper_input_language:
    voice: "{primary_voice}"
  repeat_sentence_tprs: 2
  repeat_sentence_diary: 2
  pause_between_sentences_duration: 600
  answer_silence_duration: 5000

# Template markers for diary parsing
template_diary:
  trial: '<span style="color: #C70039">Forsøk</span>:'
  answer: '<span style="color: #097969">Rettelse</span>:'
  tips: '<span style="color: #dda504">Tips</span>:'

template_tprs:
  sentence: "SETNING:"
  question: "SPØRSMÅL:"
  answer: "SVAR:"
"""


class ConfigManager:
    def __init__(self, config_dir: Path):
        self.config_dir = config_dir
        self.users_file = self.config_dir / "users.yaml"
        self.backups_dir = self.config_dir / "backups"
        self.voices_file = Path(__file__).parent / "piper_voices.yaml"

        # Ensure directories exist
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.backups_dir.mkdir(parents=True, exist_ok=True)

        # Ensure users.yaml exists
        if not self.users_file.exists():
            self._initialize_users_file()

        # Load users and voices
        self.users = self._load_users()
        self.voices = self._load_voices()

    def _initialize_users_file(self):
        """Create an empty users.yaml if it doesn't exist."""
        try:
            with open(self.users_file, "w") as f:
                yaml.dump({"users": {}}, f)
            os.chmod(self.users_file, 0o600)
        except Exception as e:
            print(f"ERROR: Failed to create users.yaml: {e}")
            sys.exit(1)

    def _load_users(self) -> Dict[str, Any]:
        """Load users.yaml or return empty dict if not found."""
        if not self.users_file.exists():
            return {"users": {}}
        try:
            with open(self.users_file, "r") as f:
                return yaml.safe_load(f) or {"users": {}}
        except Exception as e:
            print(f"ERROR: Failed to load users file: {e}")
            sys.exit(1)

    def _save_users(self):
        """Save users.yaml."""
        try:
            with open(self.users_file, "w") as f:
                yaml.dump(self.users, f, default_flow_style=False)
            # Restrict file permissions to owner only (security)
            os.chmod(self.users_file, 0o600)
        except Exception as e:
            print(f"ERROR: Failed to save users file: {e}")
            sys.exit(1)

    def _load_voices(self) -> Dict[str, Any]:
        """Load piper_voices.yaml or return empty dict if not found."""
        if not self.voices_file.exists():
            print(f"⚠ WARNING: Voices file not found: {self.voices_file}")
            print(
                "   Run: docker compose exec lingo-diary python scripts/discover-voices.py"
            )
            return {}
        try:
            with open(self.voices_file, "r") as f:
                config = yaml.safe_load(f) or {}
                return config.get("languages", {})
        except Exception as e:
            print(f"ERROR: Failed to load voices file: {e}")
            sys.exit(1)

    def prompt_for_username(self, existing_only=False, exclude=None) -> str:
        """Prompt for username with optional validation."""
        while True:
            username = input("\nUsername: ").strip()

            if not username:
                print("ERROR: Username cannot be empty")
                continue

            if exclude and username in exclude:
                print(f"ERROR: Username '{username}' not allowed")
                continue

            exists = username in self.users.get("users", {})

            if existing_only and not exists:
                print(f"ERROR: User '{username}' does not exist")
                continue

            if not existing_only and exists:
                print(f"ERROR: User '{username}' already exists")
                continue

            return username

    def prompt_for_password(self, confirm=True) -> str:
        """Prompt for password with optional confirmation."""
        while True:
            password = getpass.getpass("Password: ")

            if not password:
                print("ERROR: Password cannot be empty")
                continue

            if confirm:
                confirm_password = getpass.getpass("Confirm password: ")
                if password != confirm_password:
                    print("ERROR: Passwords do not match")
                    continue

            return password

    def prompt_for_language(
        self, label: str, current: Optional[str] = None
    ) -> tuple[str, str]:
        """Prompt for language name and code. Returns (name, code)."""
        while True:
            if current:
                response = input(
                    f"\n{label} [{current}] (press Enter to keep): "
                ).strip()
                if not response:
                    # Extract code from current (format: "english (en)")
                    if "(" in current and ")" in current:
                        code = current.split("(")[1].rstrip(")")
                        name = current.split("(")[0].strip()
                        return name, code
                    return current, current.lower()[:2]
            else:
                response = input(f"\n{label}: ").strip()

            if not response:
                print("ERROR: Language cannot be empty")
                continue

            # Parse format: "English (en)" or just "English"
            if "(" in response and ")" in response:
                name = response.split("(")[0].strip()
                code = response.split("(")[1].rstrip(")")
            else:
                name = response
                code = response.lower()[:2]

            return name, code

    def prompt_for_gender(self, current: Optional[str] = None) -> str:
        """Prompt for gender (male/female)."""
        choices = ["male", "female"]

        if current:
            print(f"\nGender [{current}]:")
            for i, choice in enumerate(choices, 1):
                marker = "●" if choice == current else " "
                print(f"  {marker} {i}. {choice}")
            response = input("Enter choice (or press Enter to keep): ").strip()
            if not response:
                return current
        else:
            print("\nGender:")
            for i, choice in enumerate(choices, 1):
                print(f"  {i}. {choice}")
            response = input("Enter choice: ").strip()

        try:
            idx = int(response) - 1
            if 0 <= idx < len(choices):
                return choices[idx]
        except (ValueError, IndexError):
            pass

        print("ERROR: Invalid choice")
        return self.prompt_for_gender(current)

    def prompt_for_voice(
        self, label: str, lang_code: str, gender: str, current: Optional[str] = None
    ) -> str:
        """Prompt for voice selection by language and gender."""
        available_voices = self.voices.get(lang_code, {}).get(gender, [])

        if not available_voices:
            print(f"\n⚠ WARNING: No {gender} voices available for {lang_code}")
            response = input(f"{label} (enter manually): ").strip()
            if not response and current:
                print(f"Keeping current: {current}")
                return current
            return response

        print(f"\n{label} ({gender} voices for {lang_code}):")
        for i, voice in enumerate(available_voices, 1):
            marker = "●" if voice == current else " "
            print(f"  {marker} {i:2}. {voice}")

        while True:
            response = input("Enter choice (or press Enter to keep current): ").strip()

            if not response:
                if current:
                    print(f"Keeping current: {current}")
                    return current
                print("ERROR: Must select a voice")
                continue

            try:
                idx = int(response) - 1
                if 0 <= idx < len(available_voices):
                    return available_voices[idx]
            except ValueError:
                pass

            print(f"ERROR: Invalid choice (1-{len(available_voices)})")

    def prompt_for_openai_key(self, current: Optional[str] = None) -> str:
        """Prompt for OpenAI API key with security warnings."""
        print("\n" + "=" * 70)
        print("OpenAI API Key Security Warning")
        print("=" * 70)
        print("The OpenAI key will be stored in plaintext in config.yaml.")
        print("IMPORTANT:")
        print("  1. Ensure file permissions are restricted (chmod 600)")
        print("  2. Do NOT commit this file to version control")
        print("  3. Keep this key secret — anyone with it can use your API quota")
        print("  4. Consider rotating keys periodically")
        print("=" * 70)

        if current:
            masked = (
                current[:10] + "..." + current[-4:] if len(current) > 14 else "*" * 8
            )
            response = input(f"\nOpenAI Key [{masked}] (press Enter to keep): ").strip()
            if not response:
                return current
        else:
            response = input("\nOpenAI Key: ").strip()

        if not response:
            print("ERROR: OpenAI key cannot be empty")
            return self.prompt_for_openai_key(current)

        return response

    def add_user(self):
        """Interactive flow to add a new user."""
        print("\n" + "=" * 70)
        print("Add New User")
        print("=" * 70)

        username = self.prompt_for_username(existing_only=False)
        password = self.prompt_for_password(confirm=True)
        primary_lang_name, primary_lang_code = self.prompt_for_language(
            "Primary Language (e.g., 'English (en)')"
        )
        study_lang_name, study_lang_code = self.prompt_for_language(
            "Study Language (e.g., 'Norwegian (no)')"
        )
        gender = self.prompt_for_gender()
        study_voice = self.prompt_for_voice(
            "Study Language Voice", study_lang_code, gender
        )
        primary_voice = self.prompt_for_voice(
            "Primary Language Voice", primary_lang_code, gender
        )
        openai_key = self.prompt_for_openai_key()

        # Hash password
        password_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

        # Add user to users.yaml
        if "users" not in self.users:
            self.users["users"] = {}

        self.users["users"][username] = {
            "password": password_hash,
            "language": primary_lang_code,
        }

        self._save_users()
        print(f"✓ User '{username}' added to users.yaml")

        # Create user config directory and config.yaml
        user_config_dir_path = self.config_dir / username
        user_config_dir_path.mkdir(exist_ok=True)

        config_content = DEFAULT_CONFIG_TEMPLATE.format(
            username=username,
            openai_key=openai_key,
            gender=gender,
            primary_language=primary_lang_name,
            primary_language_code=primary_lang_code,
            study_language=study_lang_name,
            study_language_code=study_lang_code,
            study_voice=study_voice,
            primary_voice=primary_voice,
        )

        config_file = user_config_dir_path / "config.yaml"
        try:
            with open(config_file, "w") as f:
                f.write(config_content)
            os.chmod(config_file, 0o600)  # Restrict permissions for security
            print(f"✓ Config created: {config_file}")
        except Exception as e:
            print(f"ERROR: Failed to create config: {e}")
            # Clean up the user entry
            del self.users["users"][username]
            self._save_users()
            sys.exit(1)

        print(f"\n✓ User '{username}' set up successfully!")

    def modify_user(self, username: Optional[str] = None):
        """Interactive flow to modify an existing user's configuration."""
        if not username:
            username = self.prompt_for_username(existing_only=True)

        print(f"\n" + "=" * 70)
        print(f"Modify User: {username}")
        print("=" * 70)

        user_config_file = self.config_dir / username / "config.yaml"

        if not user_config_file.exists():
            print(f"ERROR: Config file not found: {user_config_file}")
            sys.exit(1)

        try:
            with open(user_config_file, "r") as f:
                current_config = yaml.safe_load(f) or {}
        except Exception as e:
            print(f"ERROR: Failed to load config: {e}")
            sys.exit(1)

        # Extract current values
        current_gender = current_config.get("gender", "male")
        current_primary_lang = current_config.get("languages", {}).get(
            "primary_language", "English"
        )
        current_primary_code = current_config.get("languages", {}).get(
            "primary_language_code", "en"
        )
        current_study_lang = current_config.get("languages", {}).get(
            "study_language", "Norwegian"
        )
        current_study_code = current_config.get("languages", {}).get(
            "study_language_code", "no"
        )
        current_study_voice = (
            current_config.get("tts", {}).get("piper", {}).get("voice", "")
        )
        current_primary_voice = (
            current_config.get("tts", {})
            .get("piper_input_language", {})
            .get("voice", "")
        )
        current_openai_key = current_config.get("openai", {}).get("key", "")

        # Prompt for changes
        print("\nPress Enter to keep current value, or enter a new value.")

        primary_lang_name, primary_lang_code = self.prompt_for_language(
            f"Primary Language", f"{current_primary_lang} ({current_primary_code})"
        )
        study_lang_name, study_lang_code = self.prompt_for_language(
            f"Study Language", f"{current_study_lang} ({current_study_code})"
        )
        gender = self.prompt_for_gender(current_gender)
        study_voice = self.prompt_for_voice(
            "Study Language Voice", study_lang_code, gender, current_study_voice
        )
        primary_voice = self.prompt_for_voice(
            "Primary Language Voice", primary_lang_code, gender, current_primary_voice
        )
        openai_key = self.prompt_for_openai_key(current_openai_key)

        # Update config
        current_config["gender"] = gender
        current_config["languages"]["primary_language"] = primary_lang_name
        current_config["languages"]["primary_language_code"] = primary_lang_code
        current_config["languages"]["study_language"] = study_lang_name
        current_config["languages"]["study_language_code"] = study_lang_code
        current_config["tts"]["piper"]["voice"] = study_voice
        current_config["tts"]["piper_input_language"]["voice"] = primary_voice
        current_config["openai"]["key"] = openai_key

        # Save updated config
        try:
            with open(user_config_file, "w") as f:
                yaml.dump(current_config, f, default_flow_style=False)
            os.chmod(user_config_file, 0o600)
            print(f"\n✓ Config updated: {user_config_file}")
        except Exception as e:
            print(f"ERROR: Failed to save config: {e}")
            sys.exit(1)

        print(f"✓ User '{username}' configuration updated successfully!")

    def delete_user(self, username: Optional[str] = None):
        """Interactive flow to delete a user (with backup)."""
        if not username:
            username = self.prompt_for_username(existing_only=True)

        print(f"\n" + "=" * 70)
        print(f"Delete User: {username}")
        print("=" * 70)
        print(
            f"\nWARNING: This will back up and remove all configuration for '{username}'."
        )

        confirm = input(f"Type '{username}' to confirm deletion: ").strip()
        if confirm != username:
            print("Deletion cancelled.")
            return

        user_config_dir_path = self.config_dir / username

        if user_config_dir_path.exists():
            # Create backup
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_file = self.backups_dir / f"{username}_{timestamp}.tar.gz"

            try:
                with tarfile.open(backup_file, "w:gz") as tar:
                    tar.add(user_config_dir_path, arcname=username)
                print(f"✓ Config backed up to: {backup_file}")
            except Exception as e:
                print(f"ERROR: Failed to create backup: {e}")
                print("Deletion cancelled to preserve data.")
                sys.exit(1)

            # Remove config directory
            import shutil

            try:
                shutil.rmtree(user_config_dir_path)
                print(f"✓ Config directory removed: {user_config_dir_path}")
            except Exception as e:
                print(f"ERROR: Failed to remove config directory: {e}")
                sys.exit(1)

        # Remove user from users.yaml
        if username in self.users.get("users", {}):
            del self.users["users"][username]
            self._save_users()
            print(f"✓ User removed from users.yaml")

        print(f"\n✓ User '{username}' deleted successfully!")

    def list_users(self):
        """Display all users and their interface languages."""
        users = self.users.get("users", {})

        if not users:
            print("No users found.")
            return

        print("\n" + "=" * 70)
        print("Registered Users")
        print("=" * 70)
        for username, data in sorted(users.items()):
            lang = data.get("language", "unknown")
            config_file = self.config_dir / username / "config.yaml"
            exists = "✓" if config_file.exists() else "✗"
            print(f"  {exists} {username:20} (interface: {lang})")

    def show_menu(self):
        """Display interactive menu."""
        while True:
            print("\n" + "=" * 70)
            print("LingoDiary User Configuration Manager")
            print("=" * 70)
            print("\nOptions:")
            print("  1. Add User")
            print("  2. Modify User")
            print("  3. Delete User")
            print("  4. List Users")
            print("  5. Exit")

            choice = input("\nEnter choice (1-5): ").strip()

            if choice == "1":
                self.add_user()
            elif choice == "2":
                self.modify_user()
            elif choice == "3":
                self.delete_user()
            elif choice == "4":
                self.list_users()
            elif choice == "5":
                print("Goodbye!")
                break
            else:
                print("Invalid choice. Please try again.")


def main():
    """Main entry point."""
    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description="LingoDiary User Configuration Manager",
        add_help=False,  # We'll handle help manually to avoid conflicts with subcommands
    )
    parser.add_argument(
        "-i",
        "--input",
        help="Path to docker-compose.yml",
        default=None,
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Config directory (overrides docker-compose.yml)",
        default=None,
    )
    parser.add_argument(
        "command",
        nargs="?",
        help="Command to run (add-user, modify-user, delete-user, list-users)",
    )
    parser.add_argument(
        "username",
        nargs="?",
        help="Username (for modify-user or delete-user)",
    )

    args = parser.parse_args()

    # Resolve config directory
    config_dir = resolve_config_dir(args.input, args.output)

    # Create manager with resolved config directory
    manager = ConfigManager(config_dir)

    if args.command:
        command = args.command.lower()

        if command == "add-user":
            manager.add_user()
        elif command == "modify-user":
            manager.modify_user(args.username)
        elif command == "delete-user":
            manager.delete_user(args.username)
        elif command == "list-users":
            manager.list_users()
        else:
            print(f"Unknown command: {command}")
            print("\nUsage:")
            print("  python scripts/manage-config.py [command] [options]")
            print("\nCommands:")
            print("  add-user            Add a new user")
            print("  modify-user         Modify a user's configuration")
            print("  delete-user         Delete a user")
            print("  list-users          List all users")
            print("\nOptions:")
            print("  -i, --input FILE    Path to docker-compose.yml")
            print("  -o, --output DIR    Config directory")
            sys.exit(1)
    else:
        # Interactive menu
        manager.show_menu()


if __name__ == "__main__":
    main()
